# Generated by Django 5.2.4 on 2025-08-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(help_text='Ej: Bodega Principal, Sucursal Norte, Almacén Central', max_length=100, verbose_name='Nombre de la Bodega')),
                ('direccion', models.CharField(blank=True, help_text='Dirección física detallada de la bodega.', max_length=255, null=True, verbose_name='Dirección')),
                ('ciudad', models.ForeignKey(help_text='Ubicación geográfica de la bodega.', on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='terceros.ciudad', verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='empresa.empresa', verbose_name='Empresa Propietaria')),
                ('responsable', models.ForeignKey(blank=True, help_text='Tercero responsable de la gestión de la bodega.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_a_cargo', to='terceros.tercero', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
