# Generated by Django 5.2.4 on 2025-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
