# Generated by Django 5.2.4 on 2025-08-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.ciudad', verbose_name='Ciudad (Domicilio Fiscal)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tipoidentificacion', verbose_name='Tipo de Identificación'),
        ),
    ]
