# Generated by Django 5.2.4 on 2025-08-12 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='empresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios con Acceso'),
        ),
    ]
